# GitHub Pages Configuration
title: Python Template Documentation
description: A modern Python project template with comprehensive tooling and documentation
theme: jekyll-theme-minimal

# Optional: Custom domain
# url: "https://yourdomain.com"
# baseurl: "/python-template"

# Navigation
navigation:
  - title: Home
    url: /
  - title: GitHub
    url: https://github.com/username/python-template
  - title: Issues
    url: https://github.com/username/python-template/issues